<?php

/**
 * @file
 * Hooks and callbacks for migrate_exmaple_paths.
 */

/**
 * Implements hook_migration_plugins_alter().
 */
function migrate_example_paths_migration_plugins_alter(array &$migrations) {
  // For migrations with the tag 'migrate-example-paths', use CSV files
  // provided in the module's 'import' directory.
  foreach ($migrations as &$migration) {
    if (in_array('migrate-example-paths', $migration['migration_tags'])) {
      $path =& $migration['source']['path'];
      $path = drupal_get_path('module', 'migrate_example_paths') .
        '/import/' . $path;
    }
  }
}
